"""initial schema

Revision ID: 760c1fb00c8b
Revises:
Create Date: 2026-06-24 00:39:31.102228

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '760c1fb00c8b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creatives', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('creatives', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('creatives', sa.Column('recommendations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creatives', 'recommendations')
    op.drop_column('creatives', 'weaknesses')
    op.drop_column('creatives', 'strengths')
    # ### end Alembic commands ###
